"""Shared community workflow limits and spatial thresholds."""

OFFICIAL_PRIORITY_KM = 5.0
PEER_REVIEW_RADIUS_KM = 3.0
PUBLIC_REPORT_MAX_AGE_MINUTES = 180.0
DAILY_REPORT_LIMIT = 6
DAILY_REVIEW_REWARD_LIMIT = 5
